Pipelines:
 QCcontrol: ["fastqc", "abyss", "trimmomatic", "kmergenie", "align"]
 assemble: ["abyss", "allpaths", "cabog",  "masurca", "soapdenovo", "spades", "trinity"]
 evaluate: ["align", "BUSCO"]
 align: []
Tools:
 fastqc:
  bin: /sw/apps/bioinfo/fastqc/0.11.2/irma/fastqc 
  options: [--threads,  "16" ,  --outdir,  fastqc, --extract]
 trimmomatic:
  bin: /sw/apps/bioinfo/trimmomatic/0.32/irma/trimmomatic.jar 
  options: [""]
 bwa:
  bin: /sw/apps/bioinfo/bwa/0.7.4/irma/bin/bwa 
  options: ""
 picard:
  bin: /sw/apps/bioinfo/picard/1.92/irma/ 
  options: ""
 samtools:
  bin: /sw/apps/bioinfo/samtools/0.1.19/irma/bin/samtools 
  options: ""
 abyss:
  bin: /sw/apps/bioinfo/abyss/1.3.5/irma/bin/ 
  options: [""]
 abyss_mergePairs:
  bin: /sw/apps/bioinfo/abyss/1.3.5/irma/bin/abyss-mergepairs
  options: ["-m 20", "-1 230", "-2 230"]
 allpaths:
  bin: /sw/apps/bioinfo/allpathslg/52485/irma/bin/ 
  options: ["PLOIDY=2"]
 cabog:
  bin: /sw/apps/bioinfo/cabog/8.3/irma/Linux-amd64/bin/ 
  options: [""]
 masurca:
  bin: /sw/apps/bioinfo/MaSuRCA/2.3.2/irma/
  options: [""]
 soapdenovo:
  bin: /sw/apps/bioinfo/SOAPdenovo/2.04-r240/irma/bin/SOAPdenovo-63mer 
  options: [""]
 spades:
  bin: /sw/apps/bioinfo/spades/3.6.0/irma/bin/spades.py 
  options: ["--careful", "-t 8"]
 trinity:
  bin: /sw/apps/bioinfo/trinity/2014-07-17/irma/ 
  options: []
 BUSCO:
  bin: /sw/apps/bioinfo/BUSCO/1.1b1/irma/BUSCO
  options:  ["-m", "genome", "-f"]
 kmergenie:
  bin: /lupus/ngi/production/latest/KmerGenie/kmergenie
  options: [""]
